services:
  mysql_source:
    image: mysql:8.4
    hostname: mysql_source
    container_name: mysql_source
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_PORT: 3306
      MYSQL_USER: mydb_user
      MYSQL_PASSWORD: mydb_pwd
      MYSQL_DATABASE: db
      MYSQL_REPLICA_USER: '${MYSQL_REPLICA_USER}'
      MYSQL_REPLICA_PASSWORD: '${MYSQL_REPLICA_PASS}'
    ports:
      - 4406:3306
    volumes:
      - ./source/conf:/etc/mysql/conf.d
      - ./source/init/:/docker-entrypoint-initdb.d/
      - mysql_source:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h localhost -uroot -p${MYSQL_ROOT_PASSWORD}
      interval: 5s
      timeout: 5s
      retries: 20

  mysql_replica:
    image: mysql:8.4
    hostname: mysql_replica
    container_name: mysql_replica
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_PORT: 3306
      MYSQL_USER: '${MYSQL_REPLICA_USER}'
      MYSQL_PASSWORD: '${MYSQL_REPLICA_PASS}'
      MYSQL_DATABASE: db
    ports:
      - 5506:3306
    depends_on:
      mysql_source:
        condition: service_healthy
    volumes:
      - ./replica/conf:/etc/mysql/conf.d
      - ./replica/init/:/docker-entrypoint-initdb.d/
      - mysql_replica:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h localhost -uroot -p${MYSQL_ROOT_PASSWORD}
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  mysql_source:
  mysql_replica:
