#!/bin/bash

mysql -u root -p$MYSQL_ROOT_PASSWORD <<EOF
  CREATE USER "$MYSQL_REPLICA_USER"@"%" IDENTIFIED BY "$MYSQL_REPLICA_PASS"; 
  GRANT REPLICATION SLAVE ON *.* TO "$MYSQL_REPLICA_USER"@"%"; 
  FLUSH PRIVILEGES;
EOF
